/**
 * @since 14 Agosto
 * @version 3.0
 * @author Anthony Mora Parra
 * @Universidad Estatal a Distancia
 * @Curso Programacion Intermedia
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CRUnion extends javax.swing.JFrame {

    private Conversion_Nueva conversion_nueva = new Conversion_Nueva();

    /**
     * Creates new form Prueba
     */
    public CRUnion() {
        initComponents();
        ListarClientes();
        ListarClientesDropDown();
        ListarConversiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_NombreNuevaMoneda = new javax.swing.JTextField();
        txt_AgregaPrecioCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_AgregaPrecioVenta = new javax.swing.JTextField();
        btn_AgregarNuevaMoneda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        select_TipoMoneda = new javax.swing.JComboBox<>();
        txt_NuevoPrecioCompra = new javax.swing.JTextField();
        txt_NuevoPrecioVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_ActualizaValorMoneda = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_AgregaNombreCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_AgregaApellidos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_AgregaNacionalidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_AgregaEdad = new javax.swing.JTextField();
        btn_agregar_cliente = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_AgregaID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ListaMonedas = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        select_venta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        text_monto_venta = new javax.swing.JTextField();
        btn_vender = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        select_clientes1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_listado_clientes = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SelectMonedaCompra = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_MontoCompra = new javax.swing.JTextField();
        btn_Comprar = new javax.swing.JButton();
        select_clientes = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarea_lista_conversiones = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ingrese el nombre de la nueva moneda:");

        txt_NombreNuevaMoneda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txt_AgregaPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Ingrese el precio de venta de la moneda:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Ingrese el precio de compra de la moneda:");

        txt_AgregaPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_AgregarNuevaMoneda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_AgregarNuevaMoneda.setText("Ingresar Moneda");
        btn_AgregarNuevaMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarNuevaMonedaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NombreNuevaMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AgregaPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AgregaPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btn_AgregarNuevaMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_NombreNuevaMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_AgregaPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(txt_AgregaPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarNuevaMoneda)
                    .addComponent(jButton1))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Moneda", jPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Seleccione la moneda que desea actualizar: ");

        txt_NuevoPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txt_NuevoPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Ingrese el nuevo precio de venta: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Ingrese el nuevo precio de compra:");

        btn_ActualizaValorMoneda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_ActualizaValorMoneda.setText("Actualizar Moneda");
        btn_ActualizaValorMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizaValorMonedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NuevoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select_TipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NuevoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btn_ActualizaValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(select_TipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(txt_NuevoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(txt_NuevoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(btn_ActualizaValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        jTabbedPane1.addTab("Actualizar Moneda", jPanel2);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Ingrese el nombre del Cliente:");

        txt_AgregaNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Ingrese los apellidos:");

        txt_AgregaApellidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Ingrese la nacionalidad:");

        txt_AgregaNacionalidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Ingrese la edad:");

        txt_AgregaEdad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_agregar_cliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_agregar_cliente.setText("Registrar");
        btn_agregar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_clienteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Ingrese la identificacion:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AgregaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AgregaNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_agregar_cliente)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_AgregaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_AgregaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_AgregaID, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(440, 440, 440)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_AgregaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_AgregaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addComponent(txt_AgregaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_AgregaNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txt_AgregaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_agregar_cliente)
                        .addGap(278, 278, 278))))
        );

        jTabbedPane1.addTab("Registrar Cliente", jPanel6);

        txt_ListaMonedas.setEditable(false);
        txt_ListaMonedas.setColumns(20);
        txt_ListaMonedas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_ListaMonedas.setRows(5);
        jScrollPane1.setViewportView(txt_ListaMonedas);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Lista de Monedas ingresadas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Monedas", jPanel3);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione la moneda:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Ingrese el monto que desea vender: ");

        text_monto_venta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        text_monto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_monto_ventaActionPerformed(evt);
            }
        });

        btn_vender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_vender.setText("Vender");
        btn_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venderActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Seleccione el cliente");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_monto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_clientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_vender)
                .addGap(248, 248, 248))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(select_clientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(select_venta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_monto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(btn_vender)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Venta Dolares", jPanel5);

        textarea_listado_clientes.setEditable(false);
        textarea_listado_clientes.setColumns(20);
        textarea_listado_clientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textarea_listado_clientes.setRows(5);
        jScrollPane2.setViewportView(textarea_listado_clientes);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("Lista de Clientes registrados");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        jTabbedPane1.addTab("Listar Clientes", jPanel7);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Seleccione la moneda:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Ingrese el monto que desea comprar: ");

        txt_MontoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_Comprar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Comprar.setText("Comprar");
        btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComprarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Seleccione el cliente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MontoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectMonedaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectMonedaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txt_MontoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btn_Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Compra Dolares", jPanel4);

        txtarea_lista_conversiones.setEditable(false);
        txtarea_lista_conversiones.setColumns(20);
        txtarea_lista_conversiones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtarea_lista_conversiones.setRows(5);
        jScrollPane3.setViewportView(txtarea_lista_conversiones);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("Lista del historial de las conversiones realizadas: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Lista Conversiones", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Agregar Moneda");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Boton que agrega una nueva moneda 
 * @param evt 
 */
    private void btn_AgregarNuevaMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarNuevaMonedaActionPerformed
        String AgregaNombre = txt_NombreNuevaMoneda.getText();
        Double AgregaPrecioCompra = Double.parseDouble(txt_AgregaPrecioCompra.getText());
        Double AgregarPrecioVenta = Double.parseDouble(txt_AgregaPrecioVenta.getText());
        try {
            if (conversion_nueva.Agregar_Nueva_EquivalenciaC(AgregaNombre, AgregaPrecioCompra, AgregarPrecioVenta)) {
                JOptionPane.showMessageDialog(rootPane, "La moneda se agrego correctamente");
                ListarMonedaDropDown();
                ListarMonedasTextArea();
            } else {
                JOptionPane.showMessageDialog(rootPane, "La moneda ya se encuentra registrada");
            }
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(rootPane, "Occurio un error inesperado");
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_AgregarNuevaMonedaActionPerformed
/**
 * Boton que actualiza los precios de las monedas
 * @param evt 
 */
    private void btn_ActualizaValorMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizaValorMonedaActionPerformed

        Double NuevoPrecioCompra = Double.parseDouble(txt_NuevoPrecioCompra.getText());
        Double NuevoPrecioVenta = Double.parseDouble(txt_NuevoPrecioVenta.getText());
        String NombreActualizado = (String) select_TipoMoneda.getSelectedItem();

        try {
            if (conversion_nueva.Actualizar_Valores_EquivalenciasC(NombreActualizado, NuevoPrecioCompra, NuevoPrecioVenta)) {
                JOptionPane.showMessageDialog(rootPane, "Se actualizo correctamente");
                ListarMonedaDropDown();
                ListarMonedasTextArea();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede actualizar");
            }
        } catch (Exception e) {

            //JOptionPane.showMessageDialog(rootPane, "Occurio un error inesperado");
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_ActualizaValorMonedaActionPerformed
/**
 * Boton que permite comprar monedas
 * @param evt 
 */
    private void btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComprarActionPerformed
        String TipoMoneda = (String) SelectMonedaCompra.getSelectedItem();
        Double MontoCompra = Double.parseDouble(txt_MontoCompra.getText());
        String idCliente = (String) select_clientes.getSelectedItem();
        try {
            Double ResultadoCompra = conversion_nueva.CompraDolaresC(MontoCompra, TipoMoneda);
            JOptionPane.showMessageDialog(rootPane, "El resultado de la compra fue: " + ResultadoCompra);
            registroConversionArchivo(idCliente, TipoMoneda, MontoCompra, "Conversion Compra");
            ListarConversiones();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_ComprarActionPerformed

    private void text_monto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_monto_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_monto_ventaActionPerformed
/**
 * Boton que permite vender monedas
 * @param evt 
 */
    private void btn_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venderActionPerformed
        String idCliente = (String) select_clientes.getSelectedItem();
        String TipoMoneda = (String) select_venta.getSelectedItem();
        Double MontoCompra = Double.parseDouble(text_monto_venta.getText());
        try {
            Double ResultadoCompra = conversion_nueva.VentaDolaresC(MontoCompra, TipoMoneda);
            JOptionPane.showMessageDialog(rootPane, "El resultado de la venta fue: " + ResultadoCompra);
            registroConversionArchivo(idCliente, TipoMoneda, MontoCompra, "Conversion Venta");
            ListarConversiones();
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btn_venderActionPerformed
/**
 * Boton que permite aagregar los cliente al archivo.txt
 * @param evt 
 */
    private void btn_agregar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_clienteActionPerformed
        String IDCliente = txt_AgregaID.getText();
        String AgregaNombre = txt_AgregaNombreCliente.getText();
        String AgregaApellidos = txt_AgregaApellidos.getText();
        String AgregaNacionalidad = txt_AgregaNacionalidad.getText();
        int AgregaEdad = Integer.parseInt(txt_AgregaEdad.getText());
        Cliente cliente = new Cliente(IDCliente, AgregaNombre, AgregaApellidos, AgregaNacionalidad, AgregaEdad);
        if (AgregaEdad >= 18) {
            try {
                FileWriter writer = new FileWriter("ListaClientes", true);
                BufferedWriter buffer = new BufferedWriter(writer);

                buffer.write(cliente.agregarComa());
                buffer.newLine();
                buffer.close();
                JOptionPane.showMessageDialog(rootPane, "Datos agregados correctamente");
                ListarClientes();
                ListarClientesDropDown();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No tiene la edad suficiente, intente de nuevo");
        }

/**
 * Metodo para listar monedas en el combo box.
 */
    }//GEN-LAST:event_btn_agregar_clienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void ListarMonedaDropDown() {
        select_TipoMoneda.removeAllItems();
        SelectMonedaCompra.removeAllItems();
        select_venta.removeAllItems();
        String[] ListaMonedas = conversion_nueva.ListarMonedasC();
        if (ListaMonedas.length != 0) {
            //cambio en la condicion
            for (int i = 0; i < ListaMonedas.length; i++) {
                select_TipoMoneda.addItem(ListaMonedas[i]);
                SelectMonedaCompra.addItem(ListaMonedas[i]);
                select_venta.addItem(ListaMonedas[i]);
            }
        }
    }

    /**
     * Metodo que lista las monedas en el Area de texto
     */
    public void ListarMonedasTextArea() {
        txt_ListaMonedas.setText("");
        String[] listamonedastxt = conversion_nueva.ListarMonedaCompletoC();
        if (listamonedastxt.length != 0) {
            for (int i = 0; i <= listamonedastxt.length; i++) {
                txt_ListaMonedas.append(listamonedastxt[i]);
            }
        }
    }

    /**
     * Metodo que lista los clientes del archivo de texto
     */
    public void ListarClientes() {
        textarea_listado_clientes.setText("");
        ArrayList<Cliente> clientes = new ArrayList<>();
        String datos = null;
        String[] clienteTxt = null;
        try {
            FileReader reader = new FileReader("ListaClientes");
            BufferedReader buffer = new BufferedReader(reader);
            datos = buffer.readLine();
            while ((datos = buffer.readLine()) != null) // Ciclo que imprime cada una de las lineas, que se almacenan en la variable datos.
            {
                clienteTxt = datos.split(",");
                Cliente cliente;
                cliente = new Cliente(clienteTxt[0], clienteTxt[1], clienteTxt[2], clienteTxt[3], Integer.parseInt(clienteTxt[4]));
                clientes.add(cliente);
            }
            for (Cliente obj : clientes) {
                textarea_listado_clientes.append(obj.toString() + "\n");
            }
            reader.close();//se cierra el reader.
        } catch (IOException e) {
            e.printStackTrace();//se imprime la pila de llamadas para ver d�nde est� el error.
        }
    }

    /**
     * Metodo que lista las conversiones del archivo de texto
     */
    public void ListarConversiones() {
        txtarea_lista_conversiones.setText("");
        ArrayList<String> conversiones = new ArrayList<>();
        String datos = null;
        String[] conversionTxt = null;
        try {
            FileReader reader = new FileReader("Conversiones");
            BufferedReader buffer = new BufferedReader(reader);
            datos = buffer.readLine();
            while ((datos = buffer.readLine()) != null) // Ciclo que imprime cada una de las lineas, que se almacenan en la variable datos.
            {
                conversionTxt = datos.split(",");
                String conversion = conversionTxt[0] + " " + conversionTxt[2] + " ";
                conversiones.add(conversion);
            }
            for (String obj : conversiones) {
                txtarea_lista_conversiones.append(obj + "\n");
            }
            reader.close();//se cierra el reader.
        } catch (IOException e) {
            e.printStackTrace();//se imprime la pila de llamadas para ver donde esta el error.
        }
    }

    /**
     * Metodo que lista los clientes del archivo de texto para cargarlos en el dropdown
     */
    public void ListarClientesDropDown() {
        select_clientes.removeAllItems();
        select_clientes1.removeAllItems();
        ArrayList<Cliente> clientes = new ArrayList<>();
        String datos = null;
        String[] clienteTxt = null;
        try {
            FileReader reader = new FileReader("ListaClientes");
            BufferedReader buffer = new BufferedReader(reader);
            datos = buffer.readLine();
            while ((datos = buffer.readLine()) != null) // Ciclo que imprime cada una de las lineas, que se almacenan en la variable datos.
            {
                clienteTxt = datos.split(",");
                Cliente cliente;
                cliente = new Cliente(clienteTxt[0], clienteTxt[1], clienteTxt[2], clienteTxt[3], Integer.parseInt(clienteTxt[4]));
                clientes.add(cliente);
            }
            for (Cliente obj : clientes) {
                select_clientes.addItem(obj.getIdCliente());
                select_clientes1.addItem(obj.getIdCliente());
            }
            reader.close();//se cierra el reader.
        } catch (IOException e) {
            e.printStackTrace();//se imprime la pila de llamadas para ver d�nde est� el error.
        }
    }

    /**
     * Registra las conversiones que realizan los clientes en el archivo de txt
     *
     * @param idCliente
     * @param Moneda
     * @param monto
     * @param tipo
     */
    public void registroConversionArchivo(String idCliente, String Moneda, double monto, String tipo) {
        String linea = "Identificacion del cliente: " + idCliente + "," + "Moneda comprada: " + Moneda + "," + "Monto comprado: " + monto + "," + tipo + ",";
        try {
            FileWriter writer = new FileWriter("Conversiones Realizadas por el cliente: ", true);
            BufferedWriter buffer = new BufferedWriter(writer);
            buffer.write(linea);
            buffer.newLine();
            buffer.close();
            ListarClientes();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUnion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectMonedaCompra;
    private javax.swing.JButton btn_ActualizaValorMoneda;
    private javax.swing.JButton btn_AgregarNuevaMoneda;
    private javax.swing.JButton btn_Comprar;
    private javax.swing.JButton btn_agregar_cliente;
    private javax.swing.JButton btn_vender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> select_TipoMoneda;
    private javax.swing.JComboBox<String> select_clientes;
    private javax.swing.JComboBox<String> select_clientes1;
    private javax.swing.JComboBox<String> select_venta;
    private javax.swing.JTextField text_monto_venta;
    private javax.swing.JTextArea textarea_listado_clientes;
    private javax.swing.JTextField txt_AgregaApellidos;
    private javax.swing.JTextField txt_AgregaEdad;
    private javax.swing.JTextField txt_AgregaID;
    private javax.swing.JTextField txt_AgregaNacionalidad;
    private javax.swing.JTextField txt_AgregaNombreCliente;
    private javax.swing.JTextField txt_AgregaPrecioCompra;
    private javax.swing.JTextField txt_AgregaPrecioVenta;
    private javax.swing.JTextArea txt_ListaMonedas;
    private javax.swing.JTextField txt_MontoCompra;
    private javax.swing.JTextField txt_NombreNuevaMoneda;
    private javax.swing.JTextField txt_NuevoPrecioCompra;
    private javax.swing.JTextField txt_NuevoPrecioVenta;
    private javax.swing.JTextArea txtarea_lista_conversiones;
    // End of variables declaration//GEN-END:variables
}
